services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "BigDataSnowflake"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - ./db/storage/:/var/lib/postgresql/data/pgdata
