"""add facts table

Revision ID: 1ba0f6ecc1c1
Revises: d5091a74607a
Create Date: 2025-03-19 17:00:21.345171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba0f6ecc1c1'
down_revision: Union[str, None] = 'd5091a74607a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('country_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'customers', 'countries', ['country_id'], ['id'])
    op.drop_column('customers', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'country_id')
    # ### end Alembic commands ###
