"""add facts table

Revision ID: 31abbc3d8a89
Revises: 1ba0f6ecc1c1
Create Date: 2025-03-19 17:42:03.531391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31abbc3d8a89'
down_revision: Union[str, None] = '1ba0f6ecc1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customer_pets', sa.Column('breed_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'customer_pets', 'breeds', ['breed_id'], ['id'])
    op.drop_column('customer_pets', 'breed')
    op.add_column('pet_types', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('pet_types', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_types', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pet_types', 'name')
    op.add_column('customer_pets', sa.Column('breed', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_pets', type_='foreignkey')
    op.drop_column('customer_pets', 'breed_id')
    op.drop_table('breeds')
    # ### end Alembic commands ###
