"""remove secondary table between customers and pets

Revision ID: 7e1d06155d79
Revises: c1da3a429387
Create Date: 2025-03-20 15:31:50.198831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1d06155d79'
down_revision: Union[str, None] = 'c1da3a429387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_pets', sa.Column('customer_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('customer_pets_owner_id_fkey', 'customer_pets', type_='foreignkey')
    op.create_foreign_key(None, 'customer_pets', 'customers', ['customer_id'], ['id'])
    op.drop_column('customer_pets', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_pets', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_pets', type_='foreignkey')
    op.create_foreign_key('customer_pets_owner_id_fkey', 'customer_pets', 'customers', ['owner_id'], ['id'])
    op.drop_column('customer_pets', 'customer_id')
    # ### end Alembic commands ###
