"""change sales table to facts table

Revision ID: 9d5b5c7b4058
Revises: 2457d49b7903
Create Date: 2025-03-20 15:24:46.009974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5b5c7b4058'
down_revision: Union[str, None] = '2457d49b7903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='facts_customer_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='facts_product_id_fkey'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='facts_sale_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name='facts_seller_id_fkey'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='facts_store_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='facts_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='facts_pkey')
    )
    # ### end Alembic commands ###
