"""add raw data table

Revision ID: b2f92fd08e9b
Revises: 
Create Date: 2025-03-19 13:24:27.699993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f92fd08e9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('customer_first_name', sa.String(), nullable=False),
    sa.Column('customer_last_name', sa.String(), nullable=False),
    sa.Column('customer_age', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_country', sa.String(), nullable=False),
    sa.Column('customer_postal_code', sa.String(), nullable=False),
    sa.Column('customer_pet_type', sa.String(), nullable=False),
    sa.Column('customer_pet_name', sa.String(), nullable=False),
    sa.Column('customer_pet_breed', sa.String(), nullable=False),
    sa.Column('seller_first_name', sa.String(), nullable=False),
    sa.Column('seller_last_name', sa.String(), nullable=False),
    sa.Column('seller_email', sa.String(), nullable=False),
    sa.Column('seller_country', sa.String(), nullable=False),
    sa.Column('seller_postal_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('product_price', sa.String(), nullable=False),
    sa.Column('product_quantity', sa.String(), nullable=False),
    sa.Column('sale_date', sa.String(), nullable=False),
    sa.Column('sale_customer_id', sa.String(), nullable=False),
    sa.Column('sale_seller_id', sa.String(), nullable=False),
    sa.Column('sale_product_id', sa.String(), nullable=False),
    sa.Column('sale_quantity', sa.String(), nullable=False),
    sa.Column('sale_total_price', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_location', sa.String(), nullable=False),
    sa.Column('store_city', sa.String(), nullable=False),
    sa.Column('store_state', sa.String(), nullable=False),
    sa.Column('store_country', sa.String(), nullable=False),
    sa.Column('store_phone', sa.String(), nullable=False),
    sa.Column('store_email', sa.String(), nullable=False),
    sa.Column('pet_category', sa.String(), nullable=False),
    sa.Column('product_weight', sa.String(), nullable=False),
    sa.Column('product_color', sa.String(), nullable=False),
    sa.Column('product_size', sa.String(), nullable=False),
    sa.Column('product_brand', sa.String(), nullable=False),
    sa.Column('product_material', sa.String(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('product_rating', sa.String(), nullable=False),
    sa.Column('product_reviews', sa.String(), nullable=False),
    sa.Column('product_release_date', sa.String(), nullable=False),
    sa.Column('product_expiry_date', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('supplier_contact', sa.String(), nullable=False),
    sa.Column('supplier_email', sa.String(), nullable=False),
    sa.Column('supplier_phone', sa.String(), nullable=False),
    sa.Column('supplier_address', sa.String(), nullable=False),
    sa.Column('supplier_city', sa.String(), nullable=False),
    sa.Column('supplier_country', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    # ### end Alembic commands ###
