"""remove secondary table between customers and pets

Revision ID: c1da3a429387
Revises: 9d5b5c7b4058
Create Date: 2025-03-20 15:29:15.385612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1da3a429387'
down_revision: Union[str, None] = '9d5b5c7b4058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers_and_pets')
    op.add_column('customer_pets', sa.Column('owner_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'customer_pets', 'customers', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_pets', type_='foreignkey')
    op.drop_column('customer_pets', 'owner_id')
    op.create_table('customers_and_pets',
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pet_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customers_and_pets_customer_id_fkey'),
    sa.ForeignKeyConstraint(['pet_id'], ['customer_pets.id'], name='customers_and_pets_pet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customers_and_pets_pkey')
    )
    # ### end Alembic commands ###
