"""add facts table

Revision ID: d5091a74607a
Revises: 1b8ed3cb7e05
Create Date: 2025-03-19 16:47:14.949795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5091a74607a'
down_revision: Union[str, None] = '1b8ed3cb7e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_pets', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'customer_pets', 'pet_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_pets', type_='foreignkey')
    op.drop_column('customer_pets', 'category_id')
    # ### end Alembic commands ###
