"""add nullable to fields

Revision ID: d62df54bf519
Revises: e9831c78af94
Create Date: 2025-03-20 16:38:00.813611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62df54bf519'
down_revision: Union[str, None] = 'e9831c78af94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sellers', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sellers', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
