"""add seller country_id field

Revision ID: e0ed1d174621
Revises: ed5e775c225d
Create Date: 2025-03-19 21:19:50.580444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ed1d174621'
down_revision: Union[str, None] = 'ed5e775c225d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('ForeignKey', sa.Integer(), nullable=False))
    op.drop_column('sellers', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sellers', 'ForeignKey')
    # ### end Alembic commands ###
