"""add seller country_id field

Revision ID: e8dcb62ad684
Revises: e0ed1d174621
Create Date: 2025-03-19 21:20:35.317381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8dcb62ad684'
down_revision: Union[str, None] = 'e0ed1d174621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('country_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'sellers', 'countries', ['country_id'], ['id'])
    op.drop_column('sellers', 'ForeignKey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('ForeignKey', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_column('sellers', 'country_id')
    # ### end Alembic commands ###
