"""add nullable to fields

Revision ID: e9831c78af94
Revises: 7e1d06155d79
Create Date: 2025-03-20 16:29:16.082771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9831c78af94'
down_revision: Union[str, None] = '7e1d06155d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_pets', 'type_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('customer_pets', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('customer_pets', 'breed_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('customer_pets', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('customers', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'color_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'brand_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('products', 'material_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('raw_data', 'customer_first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_age',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_pet_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_pet_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'customer_pet_breed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'seller_first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'seller_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'seller_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'seller_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'seller_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_quantity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'sale_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'sale_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'sale_seller_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'sale_product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'sale_quantity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'sale_total_price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'store_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'pet_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_weight',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_material',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_reviews',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_release_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'product_expiry_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('raw_data', 'supplier_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sales', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sales', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sellers', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('stores', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('stores', 'state_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('stores', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('suppliers', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('suppliers', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('suppliers', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('stores', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('stores', 'state_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('stores', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sellers', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sales', 'product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sales', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('sales', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'supplier_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_expiry_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_release_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_reviews',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_material',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_weight',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'pet_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'store_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'sale_total_price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'sale_quantity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'sale_product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'sale_seller_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'sale_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'sale_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_quantity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'seller_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'seller_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'seller_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'seller_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'seller_first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_pet_breed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_pet_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_pet_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_age',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('raw_data', 'customer_first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'material_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'brand_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'color_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('customers', 'country_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('customer_pets', 'customer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('customer_pets', 'breed_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('customer_pets', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('customer_pets', 'type_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
